version: '3.8'

services:
  app:
    build: .
    container_name: loop-together-app
    ports:
      - "3000:3000"  # Frontend port
      - "5000:5000"  # Backend port
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/carpool
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: loop-together-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge 