const rides = [
    {
      id: 1,
      day: "Saturday",
      date: "Dec 7",
      driverName: "Ali Ahmad",
      time: "9:30 AM",
      departureLocation: "Gulshan, Karachi",
      destination: "Clifton, Karachi",
      price: 300,
    },
    {
        id: 2,
        day: "Saturday",
        date: "Dec 7",
        driverName: "Ali Ahmad",
        time: "9:30 AM",
        departureLocation: "Gulshan, Karachi",
        destination: "Clifton, Karachi",
        price: 300,
      },
      {
        id: 3,
        day: "Saturday",
        date: "Dec 7",
        driverName: "Ali Ahmad",
        time: "9:30 AM",
        departureLocation: "Gulshan, Karachi",
        destination: "Clifton, Karachi",
        price: 300,
      },
    {
      id: 4,
      day: "Sunday",
      date: "Dec 8",
      driverName: "Sara Khan",
      time: "11:00 AM",
      departureLocation: "DHA, Lahore",
      destination: "Mall Road, Lahore",
      price: 500,
    },
    {
        id: 5,
        day: "Sunday",
        date: "Dec 11",
        driverName: "Sara Khan",
        time: "11:00 AM",
        departureLocation: "DHA, Lahore",
        destination: "Mall Road, Lahore",
        price: 500,
      },
      {
        id: 6,
        day: "Wednesday",
        date: "Dec 11",
        driverName: "Sara Khan",
        time: "11:00 AM",
        departureLocation: "DHA, Lahore",
        destination: "Mall Road, Lahore",
        price: 500,
      },
  ];
  
  export default rides; 